### ISSUE TITLE
No `elm` in 0.15 OS X binaries

### ISSUE THREAD

**Issue by rtfeldman** [kevva/elm-bin#11]
If I `npm install -g elm` on OS X, I get all the individual `elm-` commands, but I do not get the master `elm` command that rules them all, and in the darkness binds them.

**Comment by passy** [comment]
I thought that was no longer a thing, Richard. Is that still included in
the other Elm distributions?

**Comment by rtfeldman** [comment]
It came back in 0.15 :smiley: 

The 0.15 installers include it.

**Comment by passy** [comment]
Oh, thanks for the info. Definitely a bug then!
