### ISSUE TITLE
  ✖ No binary found matching your system. It's probably not supported.

### ISSUE THREAD

**Issue by raould** [kevva/elm-bin#17]
hi, Any thoughts on what I might need / be doing wrong?

Ubuntu 14.04 x86.

% sudo npm install -g elm

[lots of stuff and then]

> elm@1.5.1 postinstall /usr/local/lib/node_modules/elm
> node lib/install.js

  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm pre-build test failed
  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-doc pre-build test failed
  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-make pre-build test failed
  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-package pre-build test failed
  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-reactor pre-build test failed
  ✖ No binary found matching your system. It's probably not supported.
  ✖ elm-repl pre-build test failed

elm@1.5.1 /usr/local/lib/node_modules/elm
├── async-each-series@0.1.1
├── logalot@2.1.0 (figures@1.3.5, squeak@1.2.0)
└── bin-wrapper@3.0.2 (lazy-req@1.0.0, os-filter-obj@1.0.3, each-async@1.1.1, bin-check@2.0.0, bin-version-check@2.1.0, download@4.1.2)

**Comment by raould** [comment]
$ file `which elm-doc`
/usr/local/bin/elm-doc: symbolic link to `../lib/node_modules/elm/bin/elm-doc' 
t$ ls /usr/local/lib/node_modules/elm/bin/
elm*  elm-doc*	elm-make*  elm-package*  elm-reactor*  elm-repl*

**Comment by jvoigtlaender** [comment]
I'm not an expert in `npm` matters, but: Can you also show us what kind of file that latter `elm-doc` is? Is it a true binary, or a (shell) script of some sort? In the latter case, what is its content?

So, what are the outputs of `ls -la /usr/local/lib/node_modules/elm/bin/elm-doc` and `cat /usr/local/lib/node_modules/elm/bin/elm-doc`, respectively?

**Comment by raould** [comment]
same sort of thing for all the elm-* binaries e.g. elm-make:

$ which elm-make
/usr/local/bin/elm-make
$ file `which elm-make`
/usr/local/bin/elm-make: symbolic link to `../lib/node_modules/elm/bin/elm-make' 
$ file /usr/local/lib/node_modules/elm/bin/elm-make
/usr/local/lib/node_modules/elm/bin/elm-make: Node.js script, ASCII text executable
$ cat /usr/local/lib/node_modules/elm/bin/elm-make
#!/usr/bin/env node
'use strict';

var spawn = require('child_process').spawn;
var bin = require('../')['elm-make'];
var input = process.argv.slice(2);

spawn(bin, input, {stdio: 'inherit'})
	.on('exit', process.exit);

$ which node
/usr/bin/node
$ file `which node`
/usr/bin/node: symbolic link to `/usr/bin/nodejs' 
$ node -v
v0.10.25

**Comment by raould** [comment]
$ elm-make vessel.elm 
execvp(): No such file or directory

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

**Comment by jvoigtlaender** [comment]
Is there also a directory `/usr/local/lib/node_modules/elm/vendor`? Does it contain actual binaries? Are they runnable on your system?

**Comment by raould** [comment]
Thanks for your help. There's is not any vendor folder at all in /usr/local/lib/node_modules/elm.

$ ls /usr/local/lib/node_modules/elm/
bin/  index.js	lib/  node_modules/  package.json  readme.md  share/

$ find /usr/local/lib/node_modules/elm/ -name elm-make
/usr/local/lib/node_modules/elm/bin/elm-make
(nothing else found)

**Comment by shinnn** [comment]
> Ubuntu 14.04 x86.

This repository doesn't include any pre-built binaries for 32bit Linux. https://github.com/kevva/elm-bin/tree/3c80f1c3d155fecc025bd7fb092907998eb300b3/vendor

**Comment by jvoigtlaender** [comment]
So there you have the problem. That `vendor` directory should contain the binaries for your OS, but the installer does not have access to binaries for your specific case.

**Comment by shinnn** [comment]
> $ node -v
> v0.10.25

@raould You are using the really older Node. Regardless of this issue I strongly recommend using the latest [io.js](https://iojs.org/) or Node.

**Comment by raould** [comment]
Thanks everybody.

Is there no intention of supporting x86? 

If not it would probably be nice to have clear messaging up front and/or clearer error messages :-)

**Comment by kevva** [comment]
I don't know, I'm not using this myself. But if someone is willing to compile binaries, then sure.
