### ISSUE TITLE
Symlinking `nodejs` to `node` required to install on Debian

### ISSUE THREAD

**Issue by rtfeldman** [kevva/elm-bin#18]
Per https://groups.google.com/forum/#!topic/elm-discuss/xhlUryDxs7w - apparently this fails on Debian:

```bash
sudo npm install --global elm
```

...but this works:

```bash
sudo ln -s /usr/bin/nodejs /usr/bin/node
sudo npm install --global elm
```

**Comment by kevva** [comment]
`sudo apt-get install nodejs-legacy`
