### ISSUE TITLE
Add the note about setting ELM_HOME to the npm package page.

### ISSUE THREAD

**Issue by ajhager** [kevva/elm-bin#19]
Elm reactor just will not work without this being set. It took me quite a while to figure this one out because I followed the instructions on https://www.npmjs.com/package/elm, which do not include a note about ELM_HOME.

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/elm-bin/commit/c1aa697df9f842203291d11c300fea6137ea5b40.
