### ISSUE TITLE
Update OS X binary to fix elm-package issue

### ISSUE THREAD

**Issue by rtfeldman** [kevva/elm-bin#20]
There was a bug with the OS X Installer that led to an `elm-package` binary which tried to use a specific IP for http://package.elm-lang.org - an IP that is now stale, since that server has moved. See https://groups.google.com/d/msg/elm-dev/zcba_EPBYec/bEYmj4z2Nm8J for more info.

This repo should presumably update to use the fixed OS X binary!

**Comment by evancz** [comment]
I wouldn't worry about it too much with 0.15.1 coming out.

**Comment by rtfeldman** [comment]
Obviated by https://github.com/kevva/elm-bin/issues/23
