### ISSUE TITLE
Unable to install behind proxy

### ISSUE THREAD

**Issue by Shump** [kevva/elm-bin#27]
Having set the `http_proxy` and `https_proxy` environment variables and even the `proxy` and `https-proxy` npm config settings, I am unable to install elm behind a proxy.

`npm install --global elm` prints this error message:

 :heavy_multiplication_x: Request to https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz failed
 :heavy_multiplication_x: elm pre-build test failed
 :heavy_multiplication_x: Request to https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz failed
 :heavy_multiplication_x: elm-make pre-build test failed
 :heavy_multiplication_x: Request to https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz failed
 :heavy_multiplication_x: elm-package pre-build test failed
 :heavy_multiplication_x: Request to https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz failed
 :heavy_multiplication_x: elm-reactor pre-build test failed
 :heavy_multiplication_x: Request to https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz failed
 :heavy_multiplication_x: elm-repl pre-build test failed

**Comment by kevva** [comment]
https://github.com/kevva/download/issues/64
