### ISSUE TITLE
Installation problem with NVM

### ISSUE THREAD

**Issue by calesce** [kevva/elm-bin#29]
Hi,

Using the ```npm install -g elm``` method, I had an issue with ```elm-reactor```. It appears that ```elm-reactor``` is looking for ```elm-reactor-unwrapped``` in ```/usr/local/bin```, but with NVM (installed via Homebrew), it ends up being located in ```/usr/local/Cellar/nvm/0.25.4/v0.10.39/lib/node_modules/elm/vendor/elm-reactor```. I'm not sure if this is a problem with ```elm-reactor```, this package, or something I should handle myself. 😃

**Comment by yang-wei** [comment]
Same with me.

**Comment by jvoigtlaender** [comment]
I assume this issue is the same as https://github.com/kevva/elm-bin/issues/28. See in particular [this comment](https://github.com/kevva/elm-bin/issues/28#issuecomment-121488184).
