### ISSUE TITLE
elm reactor → Could not find command `--version`

### ISSUE THREAD

**Issue by raine** [kevva/elm-bin#30]
Installed with `npm install -g elm`.

```
~/c/elm ❯❯❯ elm reactor
Could not find command `--version`. Maybe there is a typo?

Default commands include:

  make      Compile an Elm file or project into JS or HTML
  package   Manage packages from <http://package.elm-lang.org>
  reactor   Develop with compile-on-refresh and time-travel debugging
  repl      A REPL for running individual expressions

When you try to run the command `--version` we actually search for an
  executable named elm---version. Are you able to run elm---version?
  Is it on your PATH?
Elm Reactor 0.1, backed by version  of the compiler.
Listening on http://localhost:8000/
```

**Comment by jvoigtlaender** [comment]
Are you on MacOS? Maybe this is the same issue as #28, then. See in particular [this comment](https://github.com/kevva/elm-bin/issues/28#issuecomment-121488184).

**Comment by raine** [comment]
Yeah, on Mac. I have ELM_HOME set. 

Sent from my iPhone

--
Raine

**Comment by jvoigtlaender** [comment]
Sounds like this issue here could be closed, then, tracking progress on this problem in that other and pre-existing issue. (Do you see the same `elm-reactor pre-build test failed` messages on install already as people saw there? If not, then it's likely a different issue.)
