### ISSUE TITLE
node dependency not checked or documented

### ISSUE THREAD

**Issue by Zyndric** [kevva/elm-bin#33]
When using `npm install --global elm` to install elm on Debian/Ubuntu, the process bails out with message `sh: 1: node: not found`. This is a known issue and arises because Debian systems rename the node binary to nodejs. The solution is to install the package `nodejs-legacy` before installation.

However, the solution is not documented in the [readme](https://github.com/kevva/elm-bin/blob/master/readme.md). The solution is also not evident from the error message. Please put up a note in the readme. Something like: on Debian/Ubuntu systems, install the nodejs-legacy package before installation.

**Comment by jvoigtlaender** [comment]
See https://github.com/kevva/elm-bin/pull/34.

**Comment by Zyndric** [comment]
Thanks. Looks good.

**Comment by jvoigtlaender** [comment]
I think this issue can now be closed, due to the merging of #34.

**Comment by passy** [comment]
Thanks!
